export const headerLinks = [
  {
    id: 1,
    category: "bras",
    types: [
      {
        id: 1,
        type: "classic",
        category: "bras",
        // image: "https://i.imgur.com/eIDHXCN.jpg",
        image: "static/images/slider_images/classic-bra.jpg",
      },
      {
        id: 2,
        type: "push-up",
        category: "bras",
        // image: "https://i.imgur.com/HGgenw7.jpg",
        image: "static/images/slider_images/push-up.jpg",
      },
      {
        id: 3,
        type: "bralettes",
        category: "bras",
        // image: "https://i.imgur.com/wQXJEWw.jpg",
        image: "static/images/slider_images/bralette.jpg",
      },
      {
        id: 4,
        type: "triangle",
        category: "bras",
        // image: "https://i.imgur.com/kruLPSX.jpg",
        image: "static/images/slider_images/triangle.jpg",
      },
    ],
  },
  {
    id: 2,
    category: "panties",
    types: [
      {
        id: 1,
        type: "classic",
        category: "panties",
        // image: "https://i.imgur.com/CYzQQ2j.jpg",
        image: "static/images/slider_images/classic.jpg",
      },
      {
        id: 2,
        type: "thongs",
        category: "panties",
        // image: "https://i.imgur.com/PUBeFBU.jpg",
        image: "static/images/slider_images/thongs.jpg",
      },
      {
        id: 3,
        type: "brazilian",
        category: "panties",
        // image: "https://i.imgur.com/XzYQMCN.jpg",
        image: "static/images/slider_images/brazilian.jpg",
      },
      {
        id: 4,
        type: "slimming",
        category: "panties",
        // image: "https://i.imgur.com/3BQXnVY.jpg",
        image: "static/images/slider_images/slimming.jpg",
      },
    ],
  },
  {
    id: 3,
    category: "accessories",
    types: [
      {
        id: 1,
        type: "tights",
        category: "accessories",
        // image: "https://i.imgur.com/QOYIuH8.jpg",
        image: "static/images/slider_images/tights.jpg",
      },
      {
        id: 2,
        type: "bodysuits",
        category: "accessories",
        // image: "https://i.imgur.com/KEAraKa.jpg",
        image: "static/images/slider_images/bodysuits.jpg",
      },
      {
        id: 3,
        type: "socks",
        category: "accessories",
        // image: "https://i.imgur.com/s6RxIfw.jpg",
        image: "static/images/slider_images/socks.jpg",
      },
      {
        id: 4,
        type: "other",
        category: "accessories",
        // image: "https://i.imgur.com/wR76jVi.jpg",
        image: "static/images/slider_images/other.jpg",
      },
    ],
  },
  {
    id: 4,
    category: "sleepwear",
    types: [
      {
        id: 1,
        type: "long pajamas",
        category: "sleepwear",
        // image: "https://i.imgur.com/ZWsYpLI.jpg",
        image: "static/images/slider_images/long_pajamas.jpg",
      },
      {
        id: 2,
        type: "nightgowns",
        category: "sleepwear",
        // image: "https://i.imgur.com/dN8Xgjo.jpg",
        image: "static/images/slider_images/nightgown.jpg",
      },
      {
        id: 3,
        type: "robes",
        category: "sleepwear",
        // image: "https://i.imgur.com/DadlMAP.jpg",
        image: "static/images/slider_images/robes.jpg",
      },
      {
        id: 4,
        type: "short pajamas",
        category: "sleepwear",
        // image: "https://i.imgur.com/pvnreGX.jpg",
        image: "static/images/slider_images/short_pajamas.jpg",
      },
    ],
  },
];
